Added ruleId deprecation notice
codatio/codat-docs pull request #1078
Opened 2024-03-19 13:31 UTC by dcoplowe

# Description

* Include a summary of the new content you're adding or the reason for the change. 
* Include relevant context.
* Do not link to work items.
* Any PNG images should be compressed using [Tiny PNG](https://tinypng.com/) or equivalent.

## Type of change

Please delete options that are not relevant.

- [x] New document(s)/updating existing
- [ ] Fixes
- [ ] Styling
- [ ] Bug fix (non-breaking change which fixes an issue)

## Reviews and merging

You are responsible for getting your PR merged. Address review comments promptly and **make sure to merge the PR when ready**.
Feel free to 'Enable automerge' - your PR will automatically merge when accepted and passing the build.

2024-03-19 13:45 UTC, mcclowes requested changes

2024-03-19 13:45 UTC, mcclowes commented on blog/240319-deprecation-ruleId.md
> +Review and update your application logic to remove any dependencies on the `ruleId`. This will help prevent any disruptions to your integration with Codat.
```suggestion
Review and update your application logic to remove any dependencies on the `RuleId`. This will help prevent any disruptions to your integration with Codat.

You should use `RuleType` to identify what event a given webhook corresponds with.
```

2024-03-19 13:45 UTC, mcclowes commented on blog/240319-deprecation-ruleId.md
> +On **July 10, 2024**, we will deprecate the `ruleId` property in all our existing rule payloads following the release of our [new webhooks service](/updates/240306-new-webhook-service-released).
It is unclear whether this only impacts the user once the migrate to the new service

2024-03-19 13:45 UTC, mcclowes commented on blog/240319-deprecation-ruleId.md
> +The `ruleId` property will be deprecated in the following webhook rule schemas:
`RuleId` is capital R in our docs

2024-03-19 13:47 UTC, pzaichkina commented on blog/240319-deprecation-ruleId.md
> +The `ruleId` property will be deprecated in the following webhook rule schemas:
yeah, I believe that's how it is spelled in the original responses etc

2024-03-19 13:49 UTC, pzaichkina commented on blog/240319-deprecation-ruleId.md
> +On **July 10, 2024**, we will deprecate the `ruleId` property in all our existing rule payloads following the release of our [new webhooks service](/updates/240306-new-webhook-service-released).
any value in mentioning webhooks in the sentence? like, "in all our existing webhook payloads" or something

2024-03-19 13:53 UTC, pzaichkina commented on blog/240319-deprecation-ruleId.md
> +If no action is taken by the deprecation date, your application will continue to recieve events however the `ruleId` will not be populated.
```suggestion
If no action is taken, after **July 10, 2024**, your application will continue to receive events, but the `RuleId` will not be populated.
```

2024-03-19 13:53 UTC, pzaichkina commented on blog/240319-deprecation-ruleId.md
> +Depending on your implementation this would likely cause your application to stop processing Codat's webhooks.
```suggestion
Depending on your implementation, this will likely cause your application to stop processing Codat's webhooks. 
```

2024-03-19 13:53 UTC, pzaichkina commented on blog/240319-deprecation-ruleId.md
> +Any application logic using the `ruleId` property will function following your unexpected `ruleId` logic.
what does "following your unexpected ruleid logic" mean?

2024-03-19 13:57 UTC, pzaichkina commented on blog/240319-deprecation-ruleId.md
> +Any application logic using the `ruleId` property will function following your unexpected `ruleId` logic.
should this say

Any application logic that uses the `ruleId` property may function in an unexpected manner.

2024-03-20 15:34 UTC, mcclowes commented on blog/240320-deprecation-ruleId.md
> +On **July 10, 2024**, we will deprecate the `RuleId` property in all our existing webhook payloads following the release of our [new webhooks service](/updates/240306-new-webhook-service-released).
Still unclear whether this impacts only clients who've migrated to the new service or unmigrated clients too

2024-03-26 14:18 UTC, merged