Added some extra text for optimizing API responses
codatio/codat-docs pull request #1083
Opened 2024-03-21 11:20 UTC by andy-white-hat

# Description

Included some new text on the paging page to reference our recommended page size with a link to the optimization page.

## Type of change

Please delete options that are not relevant.

- [*] New document(s)/updating existing
- [ ] Fixes
- [ ] Styling
- [ ] Bug fix (non-breaking change which fixes an issue)

## Reviews and merging

You are responsible for getting your PR merged. Address review comments promptly and **make sure to merge the PR when ready**.
Feel free to 'Enable automerge' - your PR will automatically merge when accepted and passing the build.

2024-03-21 11:33 UTC, andy-white-hat commented
FYI @mcclowes 

![image](https://github.com/codatio/codat-docs/assets/49150815/d9a4bd57-4054-407d-a918-638f40888c77)

2024-03-21 13:53 UTC, mcclowes requested changes

2024-03-21 13:53 UTC, mcclowes commented on docs/using-the-api/paging.md
> +- `pageSize` : You can define the number of the results you would like to have displayed on one page. The default page size is 100, while the maximum page size can be set to 5000. We recommend that i
```suggestion
- `pageSize` : You can define the number of results you would like returned per page. The default page size is 100, while the maximum page size can be set to 5000. We recommend using the default page size to ensure optimal response times. Read more on [Optimizing API Calls](/using-the-api/optimizing-api-calls). 
```

2024-03-22 13:46 UTC, mcclowes approved these changes

2024-03-22 13:46 UTC, merged