sfe updates
codatio/codat-docs pull request #146
Opened 2023-02-21 11:59 UTC by jmyorston

# Description

updated links, tidied up pages, fixed incorrect config api reference

## Type of change

Please delete options that are not relevant.

- [x] New document(s)/updating existing
- [x] Fixes
- [ ] Styling
- [ ] Bug fix (non-breaking change which fixes an issue)

2023-02-21 12:33 UTC, pzaichkina requested changes
Please address comments

2023-02-21 12:33 UTC, pzaichkina commented on docs/sync-for-expenses/overview.md
> +      The sync for expenses api is completely standardised with a datamodel based on expense card providers.
```suggestion
      The Sync for Expenses API is completely standardised with a datamodel based on expense card providers. 
```

2023-02-21 12:33 UTC, pzaichkina commented on docs/sync-for-expenses/configandcategorize.md
> +      Choose which bank account (<code>bankAccount.id</code>) purchases will be made from, this can also be a credit card account.
```suggestion
      Choose which bank account (<code>bankAccount.id</code>) purchases will be made from. This can also be a credit card account.
```

2023-02-21 12:33 UTC, pzaichkina commented on docs/sync-for-expenses/configandcategorize.md
> +         <a href="/accounting-api#/operations/get-account">GET</a> A list of available accounts, You can use this request to retrieve a list of relevant accounts from your customers accounting softwa
```suggestion
         <a href="/accounting-api#/operations/get-account">GET</a> a list of available accounts.  
         Use this request to retrieve a list of relevant accounts from your customers' accounting software.  You should also add additional query parameters, e.g. <code>query=metadata.isDeleted=false&&isBankAccount=true</code>. 
```

2023-02-21 12:33 UTC, pzaichkina commented on docs/sync-for-expenses/configandcategorize.md
> +         You can <a href="/accounting-api#/operations/post-account">POST</a> to the accounting api to <strong>create</strong> a new account.
```suggestion
         You can <a href="/accounting-api#/operations/post-account">POST</a> to the Accounting API to <strong>create</strong> a new account.
```

2023-02-21 12:33 UTC, pzaichkina commented on docs/sync-for-expenses/configandcategorize.md
> +         <a href="/accounting-api#/operations/get-supplier">GET</a> A list of available suppliers in the companies accounting software, you can also add additional query parameters e.g. <code>query=m
```suggestion
         <a href="/accounting-api#/operations/get-supplier">GET</a> a list of available suppliers in the company's accounting software. You can also add additional query parameters, e.g. <code>query=metadata.isDeleted=false&&supplierName=supplierName</code>
```

2023-02-21 12:33 UTC, pzaichkina commented on docs/sync-for-expenses/configandcategorize.md
> +      A (<code>supplier.id</code>) is required to associate all spend against.
```suggestion
      A supplier (<code>supplier.id</code>) is required to associate all spending against that supplier. 
```

2023-02-21 12:33 UTC, pzaichkina commented on docs/sync-for-expenses/configandcategorize.md
> +      Choose which customer (<code>bankAccount.id</code>) income related activities such as cashback will be associated too.
```suggestion
      Choose which customer (<code>customer.id</code>) any income-related activities, such as cashback, should be associated with.  
```

2023-02-21 12:33 UTC, pzaichkina commented on docs/sync-for-expenses/sync-process/expense-transactions.md
> +      Is similar, to a refund in behaviour and represents a return of transaction/payment sum which may have been disputed.
```suggestion
      Is similar to a refund in behavior and represents a return of transaction or payment sum which may have been disputed.
```

2023-02-21 12:33 UTC, pzaichkina commented on docs/sync-for-expenses/sync-process/expense-transactions.md
> +      <p>Can be used to represent write-off's & transaction adjustments such as foreign exchange adjustments.
```suggestion
      <p>Can be used to represent write-offs & transaction adjustments such as foreign exchange adjustments. 
```

2023-02-21 12:33 UTC, pzaichkina commented on docs/sync-for-expenses/sync-process/expense-transactions.md
> +<p>Can be used to represent write-off's & transaction adjustments such as foreign exchange adjustments.
```suggestion
<p>Can be used to represent write-offs & transaction adjustments such as foreign exchange adjustments. 
```

2023-02-21 12:33 UTC, pzaichkina commented on docs/sync-for-expenses/sync-process/sync-process-explained.md
> +You can then initiate the sync process for multiple datasets by making an api request to the [sync endpoint](/sync-for-expenses-api#/operations/intiate-sync).
```suggestion
You can then initiate the sync process for multiple datasets by making an API request to the [sync endpoint](/sync-for-expenses-api#/operations/intiate-sync).
```

2023-02-21 12:33 UTC, pzaichkina commented on docs/sync-for-expenses/sync-process/sync-process-explained.md
>  There are three ways that you can check the status of the sync:
```suggestion
There are three ways to check the status of the sync:
```

2023-02-21 12:33 UTC, pzaichkina commented on docs/sync-for-expenses/sync-process/sync-process-explained.md
> +Once the sync has completed, you should check whether the transactions were successfully sync'd to the accounting package - this can be done via the [transaction metadata endpoint](/sync-for-expenses
```suggestion
Once the sync has completed, you should check whether the transactions were successfully synced to the accounting package. This can be done via the [transaction metadata endpoint](/sync-for-expenses-api#/operations/get-sync-transactions)
```

2023-02-21 12:33 UTC, pzaichkina commented on docs/sync-for-expenses/sync-process/sync-process-explained.md
> +To post the attachment for each transactionId. with a status of `Completed` and integrationType of `expense` they can then call the [attachment endpoint](/sync-for-expenses-api#/operations/upload-att
```suggestion
To post the attachment for each `transactionId` with a status of `Completed` and integrationType of `expense`, call the [attachment endpoint](/sync-for-expenses-api#/operations/upload-attachment)
```

2023-02-21 12:33 UTC, pzaichkina commented on docs/sync-for-expenses/sync-process/uploading-receipts.md
>  Adding a receipt to the transaction can be done after the sync, different accounting software supports different file formats and sizes so its best to check [here](/accounting-api#/attachments#option
this API link for format and size info does not lead anywhere - please check

2023-02-21 12:33 UTC, pzaichkina commented on docs/sync-for-expenses/sync-process/uploading-receipts.md
>  Adding a receipt to the transaction can be done after the sync, different accounting software supports different file formats and sizes so its best to check [here](/accounting-api#/attachments#option
```suggestion
Adding a receipt to the transaction can be done after the sync, different accounting software supports different file formats and sizes, so it is best to check [here](/accounting-api#/attachments#options-for-pushing-attachments-to-the-accounting-platform) for the supported options.
```

2023-02-21 14:38 UTC, jmyorston commented on docs/sync-for-expenses/sync-process/uploading-receipts.md
>  Adding a receipt to the transaction can be done after the sync, different accounting software supports different file formats and sizes so its best to check [here](/accounting-api#/attachments#option
see this commit for the updates https://github.com/codatio/codat-docs/pull/146/commits/e7a3d9d9c24cef6620435f0bc99c093b6bd7bd5d

2023-02-22 10:04 UTC, pzaichkina approved these changes

2023-02-22 10:04 UTC, merged