Draft: Set up local environment
codatio/codat-docs pull request #166
Opened 2023-02-23 11:09 UTC by d-laing

# Description

Initial draft for first review and to clarify the details.

## Type of change

Please delete options that are not relevant.

- [x] New document(s)/updating existing
- [ ] Fixes
- [ ] Styling
- [ ] Bug fix (non-breaking change which fixes an issue)

2023-02-23 12:39 UTC, dcoplowe requested changes
Let's dicsuss setting up webhooks in the portal.

2023-02-23 12:55 UTC, d-laing commented on docs/underwriting/set-up-local-env.md
> +   dotnet run
Right. Will that involve viewing / editing the `launchSettings` JSON file? Or do we just need an explanation of the three different profiles: HTTP, HTTPS and IIS Express?

2023-02-27 14:57 UTC, pzaichkina commented on docs/underwriting/set-up-local-env.md
> +
I think maybe the File Directory section that I wrote in the introduction should go here instead.

2023-02-28 14:14 UTC, pzaichkina approved these changes

2023-02-28 14:14 UTC, merged