Make code snippets longer than one line fenced code blocks
codatio/codat-docs pull request #179
Opened 2023-02-28 20:43 UTC by msmithcodat

# Description

Please include a summary of the new content you're adding or the reason for the change. Please include relevant context.

## Type of change

Please delete options that are not relevant.

- [ ] New document(s)/updating existing
- [ ] Fixes
- [X] Styling
- [ ] Bug fix (non-breaking change which fixes an issue)

2023-03-01 09:50 UTC, d-laing requested changes
Great job! I've made a few comments to address on some of the markup.  Thanks

2023-03-01 09:50 UTC, d-laing commented on docs/assess/metrics/accounting/api-marketing-metrics.md
> +# Parameters
Good spot.

2023-03-01 09:50 UTC, d-laing commented on docs/assess/portal/categorization-of-accounts.md
> +- The output of the endpoint below in <a href="/assess-api#/operations/get-data-companies-companyId-connections-connectionId-assess-accounts-categories">API reference</a> listing the categories.
```suggestion
- The output from the <a href="/assess-api#/operations/get-data-companies-companyId-connections-connectionId-assess-accounts-categories">List suggested and confirmed account categories</a> endpoint.
```

2023-03-01 09:50 UTC, d-laing commented on docs/auth-flow/customize/set-up-redirects.md
> +For example, if you set your Redirect URL to the URL below
It's not best practice to divide a sentence up with a code block like this, especially when it comes to future translation. Please format like this:

> For example, if you set your Redirect URL to `https://www.codat.io/{journeyType}/success?ClientType={clientType}`, then the link URLs would give the following outcomes:

2023-03-01 09:50 UTC, d-laing commented on docs/auth-flow/customize/set-up-redirects.md
> +```
Indent the backticks by three spaces - lines 82 and 83. This aligns them with the numbered steps.

2023-03-01 09:50 UTC, d-laing commented on docs/auth-flow/customize/set-up-redirects.md
> +```
Same point about spaces.

2023-03-01 09:50 UTC, d-laing commented on docs/auth-flow/customize/use-openid-connect.md
> +   ```
http :)

2023-03-01 09:50 UTC, d-laing commented on docs/integrations/accounting/dynamics365businesscentral/accounting-dynamics365businesscentral-setup.md
> +   - **Redirect URI**: Select **Web**, then enter the following URL: ` <https://dynamics365businesscentral.codat.io/oauth/callback> `
```suggestion
   - **Redirect URI**: Select **Web**, then enter the following URL: `https://dynamics365businesscentral.codat.io/oauth/callback`
```

2023-03-01 09:50 UTC, d-laing commented on docs/integrations/accounting/quickbooksdesktop/software-and-hardware-requirements.md
> +The QuickBooks Desktop connector communicates over port 443 to URLs hosted on <https://quickbooksdesktop.codat.io> in production.
```suggestion
The QuickBooks Desktop connector communicates over port 443 to URLs hosted on `https://quickbooksdesktop.codat.io` in production.
```

2023-03-01 09:50 UTC, d-laing commented on docs/integrations/accounting/quickbooksdesktop/software-and-hardware-requirements.md
> +If you experience problems with the connector transmitting data, please add the following URL to your firewall allow list: <https://quickbooksdesktop.codat.io/>
```suggestion
If you experience problems with the connector transmitting data, please add the following URL to your firewall allow list: `https://quickbooksdesktop.codat.io/`.
```

2023-03-01 09:53 UTC, d-laing commented
This should not be merged we're sure the Vercel build passes. Thanks!

2023-03-02 13:58 UTC, msmithcodat commented on docs/auth-flow/customize/use-openid-connect.md
> +   ```
updated :)

2023-03-02 13:58 UTC, msmithcodat commented on docs/auth-flow/customize/set-up-redirects.md
> +```
updated!

2023-03-02 13:58 UTC, msmithcodat commented on docs/auth-flow/customize/set-up-redirects.md
> +```
updated!

2023-03-02 14:29 UTC, d-laing approved these changes
Changes look good.

2023-03-03 10:32 UTC, merged