added platform coverage for sync for expenses
codatio/codat-docs pull request #231
Opened 2023-03-15 18:10 UTC by jmyorston

# Description

Reused the integrations component to add coverage for sync for expenses in the overview page
/sync-for-expenses/overview
Added Sync for expenses to the integrations coverage page
/integrations/all-integrations

## Type of change

Please delete options that are not relevant.

- [x] New document(s)/updating existing
- [ ] Fixes
- [ ] Styling
- [ ] Bug fix (non-breaking change which fixes an issue)

## Reviews and merging

You are responsible for getting your PR merged. Address review comments promptly and **make sure to merge the PR when ready**.
Feel free to 'Enable automerge' - your PR will automatically merge when accepted and passing the build.

2023-03-15 18:21 UTC, pzaichkina requested changes
This change has led to SfC being visible on the actual integrations list page (see bottom of the page) - https://codat-docs-git-sfeintegrationsupport-codat.vercel.app/integrations/all-integrations

I assume we don't actually want that?
![image](https://user-images.githubusercontent.com/112084241/225405991-f2fe5064-f537-4821-91b4-a332d1234723.png)

2023-03-15 19:52 UTC, jmyorston commented
> This change has led to SfC being visible on the actual integrations list page (see bottom of the page) - https://codat-docs-git-sfeintegrationsupport-codat.vercel.app/integrations/all-integrations

@pzaichkina I deliberately added these to the bottom of the page - but can remove these if you think its a bad idea

2023-03-16 09:58 UTC, mcclowes commented on src/components/page/Expenses/index.tsx
Love the use of the component here

2023-03-16 10:01 UTC, mcclowes requested changes
Integrations are organised on the All Integrations page based on category rather than Product, so need a rethink there

2023-03-16 10:01 UTC, mcclowes commented on src/components/global/Integrations/integrations.js
> +  {
So the reason this view organises things under Accountg/banking... rather than Accounting API, Banking API is because the integrations are not as per product, but rather category, and this matches with how they're organised in the settings in Portal.

As such, I don't think adding sfe stuff here in this way quite works. However, I can check out your PR and modify it a bit?

2023-03-16 10:45 UTC, jmyorston commented on src/components/global/Integrations/integrations.js
> +  {
@mcclowes - please do - I could create a standalone list in @components/page/Expenses, or maybe we could modify the integrations list to add a property for supported products?
e.g.
```
export const integrations = [{
    "name": "QuickBooks Online",
    "to": "/integrations/accounting/quickbooksonline/accounting-quickbooksonline",
    "type": "accounting",
    "img": "https://static.codat.io/public/officialLogos/Square/19EEFA32-58A8-4097-B95A-EF150BF24FA0.png",
    "supportedProducts":{
      "syncForExepenses": {
        "tag":"Credit Cards only"
      },
      "syncForCommerce":{
        "tag":"Journals and Invoice sync"
      }
    }
  },
  {
    "name": "Clear Books",
    "to": "/integrations/accounting/clearbooks/accounting-clearbooks",
    "type": "accounting",
    "img": "https://static.codat.io/public/officialLogos/Square/C23CFE49-1C1B-49BD-9192-8280B281F0C0.png"
  }...
  ]
```

2023-03-16 13:33 UTC, mcclowes commented
I've updated this branch, please review @jmyorston @pzaichkina

2023-03-16 13:34 UTC, mcclowes approved these changes

2023-03-16 14:02 UTC, merged