Async use of Link
codatio/codat-docs pull request #243
Opened 2023-03-17 18:50 UTC by pzaichkina

# Description

Documenting asynchronous use of Link.

## Type of change

- [X] New document(s)/updating existing

## Reviews and merging

You are responsible for getting your PR merged. Address review comments promptly and **make sure to merge the PR when ready**.
Feel free to 'Enable automerge' - your PR will automatically merge when accepted and passing the build.

2023-03-17 20:07 UTC, mcclowes commented on docs/auth-flow/overview.md
> +In your customer's organization, the person signing up with Codat may not have the credentials for the integration platform they want to connect. To enable them to proceed and explore the product, yo
```suggestion
In your customer's organization, the person signing up with Codat may not have their credentials to hand. To enable them to proceed and explore the product, you can make upfront authorization optional. Later, remind them to authorize, providing a clear indication of the value to them. 
```

2023-03-17 20:07 UTC, mcclowes commented on docs/auth-flow/overview.md
> +Later, approach them with a request to authorize and provide them with an option to authorize themselves, or invite someone else. This can be done via email, or within your product. If the user choos
```suggestion
The user signing up may not have access to their business' financial data at all. For best results, provide them with an option to authorize themselves, or to invite someone else to (e.g. a member of their finance team). This can be done via email, or within your product. If the user chooses to invite someone else, this will share the Link URL with the stakeholder who has the credentials for the relevant platform.
```

2023-03-20 11:24 UTC, d-laing requested changes
Great to introduce this concept into the auth flow docs. I added some comments from my perspective as someone who is new to this feature.

2023-03-20 11:24 UTC, d-laing commented on docs/auth-flow/overview.md
> +Our auth flow solution supports many real-life applications and scenarios that you can levarage regardless of the auth flow approach you choose.
```suggestion
Our auth flow solution supports many real world applications and scenarios that you can leverage regardless of the approach you take to building your auth flow.
```

2023-03-20 11:24 UTC, d-laing commented on docs/auth-flow/overview.md
> +In your customer's organization, the person signing up with Codat may not have their credentials to hand. To enable them to proceed and explore the product, you can make upfront authorization optiona
Suggestions:

the person signing up with Codat > the user signing up through Codat

"explore the product" - which product does this refer to?

2023-03-20 11:24 UTC, d-laing commented on docs/auth-flow/overview.md
> +The user signing up may not have access to their business' financial data at all. For best results, provide them with an option to authorize themselves, or to invite someone else to (e.g. a member of
business's financial data

2023-03-20 11:24 UTC, d-laing commented on docs/auth-flow/overview.md
> +- **Asynchronous use of Link**
The single bullet list looks a bit odd in the preview.

2023-03-20 11:24 UTC, d-laing commented on docs/auth-flow/overview.md
> +The user signing up may not have access to their business' financial data at all. For best results, provide them with an option to authorize themselves, or to invite someone else to (e.g. a member of
```suggestion
The user signing up may not have access to their business' financial data at all. For best results, provide them with an option to authorize themselves, or to invite someone else to (e.g. a member of their finance team). This can be done via email or within your product. If the user chooses to invite someone else, this will share the Link URL with the stakeholder who has the credentials for the relevant platform.
```

2023-03-20 11:24 UTC, d-laing commented on docs/auth-flow/overview.md
> +In your customer's organization, the person signing up with Codat may not have their credentials to hand. To enable them to proceed and explore the product, you can make upfront authorization optiona
It could be clearer _how_ they can "make upfront authorization optional".

2023-03-20 11:24 UTC, d-laing commented on docs/auth-flow/overview.md
> +
Which of the three approaches does the guidance on async use of Link relate to? Hosted Link, embedded Link or Link API?

2023-03-20 11:43 UTC, pzaichkina commented on docs/auth-flow/overview.md
> +
can be used for all three, hence no specific callout

2023-03-20 13:37 UTC, d-laing requested changes
One more comment.

2023-03-20 13:37 UTC, d-laing commented on docs/auth-flow/overview.md
> +The user signing up may not have access to their business' financial data at all. For best results, provide them with an option to authorize themselves, or to invite someone else (e.g. a member of th
Duplicated paragraph! ;)

2023-03-20 13:47 UTC, pzaichkina commented on docs/auth-flow/overview.md
> +The user signing up may not have access to their business' financial data at all. For best results, provide them with an option to authorize themselves, or to invite someone else (e.g. a member of th
...how did that happen

2023-03-20 14:41 UTC, d-laing approved these changes

2023-03-20 14:41 UTC, merged