Added basic docs
codatio/codat-docs pull request #280
Opened 2023-04-03 09:54 UTC by e-donnelly

# Description

Were deprecating V2 account categories and all related features. These are guides on what endpoints will be going and how they can migrate to the v3 equivalent. 

## Type of change

Please delete options that are not relevant.

- New document(s)/updating existing

## Reviews and merging

You are responsible for getting your PR merged. Address review comments promptly and **make sure to merge the PR when ready**.
Feel free to 'Enable automerge' - your PR will automatically merge when accepted and passing the build.

2023-04-03 13:37 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories-api-clients.md
> +| GET /data/assess/accounts/categories 	| The supported categories have changed - you can find the latest list here.  	|
this table renders really poorly in the preview - the endpoint names are too long, so they don't fit into the width of the screen. 
also, if you would like to format the text with new lines inside the table cell, please use <br/> (typed in exactly like that) where you want a line break

2023-04-03 13:54 UTC, e-donnelly commented on docs/assess/guides/migration-guides/deprecation-account-categories-api-clients.md
> +| GET /data/assess/accounts/categories 	| The supported categories have changed - you can find the latest list here.  	|
@pzaichkina what would you recommend instead here?

2023-04-03 14:26 UTC, pzaichkina requested changes

2023-04-03 14:26 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories-api-clients.md
> +| PATCH /data/companies/{companyId}/connections/{connectionId}/assess/accounts/categories; and PATCH /data/companies/{companyId}/connections/{connectionId}/assess/accounts/{accountId}/categories 	| I
```suggestion
| PATCH /data/companies/{companyId}/connections/{connectionId}/assess/accounts/categories<br/> PATCH /data/companies/{companyId}/connections/{connectionId}/assess/accounts/{accountId}/categories 	| You may want to recategorize accounts so that the model learns and improves for your companies. To do so:<br/>1. Log into the Codat portal <br/>2. Select a company on the **Companies** page <br/>3. Click the **Categorize Accounts** button <br/>4. Ensure the **Version** drop-down on the top right is set to _Version 3_ <br/>We have revamped this screen and included new features that simplify account categorization, including Confidence level. <br/>**Note**: In the latest version we no longer support recategorization via API. If you used to recategorize because the Enhanced Profit and Loss / Balance Sheet was not being returned due to uncategorized accounts, note that the latest endpoints do not have this restriction. <br/>If you do not need model learning for your companies, you do not need to recategorize via Codat and can make amendments in your own environment. 	|

```

2023-04-03 14:26 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories-api-clients.md
> +| GET /data/companies{companyId}/connections/{connectionId}/assess/enhancedBalanceSheet 	| [GET /companies/{companyId}/data/financials/balanceSheet/accounts](/assess-api#/operations/get-accounts-for-
```suggestion
| GET /data/companies{companyId}/connections/{connectionId}/assess/enhancedBalanceSheet 	| [GET /companies/{companyId}/data/financials/balanceSheet/accounts](/assess-api#/operations/get-accounts-for-enhanced-balance-sheet) <br/>Note: the response schema has changed. 	|

```

2023-04-03 14:26 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories-api-clients.md
> +| GET /data/companies{companyId}/connections/{connectionId}/assess/enhancedProfitandLoss 	| [GET /companies/{companyId}/data/financials/profitAndLoss/accounts](/assess-api#/operations/get-accounts-fo
```suggestion
| GET /data/companies{companyId}/connections/{connectionId}/assess/enhancedProfitandLoss 	| [GET /companies/{companyId}/data/financials/profitAndLoss/accounts](/assess-api#/operations/get-accounts-for-enhanced-profit-and-loss) <br/>Note: the response schema has changed. 	|

```

2023-04-03 14:26 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories-api-clients.md
> +| GET /data/companies/{companyId}/connections/{connectionId}/assess/financialMetrics; and GET /data/companies/{companyId}/connections/{connectionId}/assess/accountingMetrics/marketing 	| We are no lo
```suggestion
| GET /data/companies/{companyId}/connections/{connectionId}/assess/financialMetrics; and GET /data/companies/{companyId}/connections/{connectionId}/assess/accountingMetrics/marketing 	| We no longer support the precalculated metrics available on this endpoint. Calculate your own using our new endpoints: <br/>[GET /companies/{companyId}/data/financials/profitAndLoss/accounts](/assess-api#/operations/get-accounts-for-enhanced-profit-and-loss) <br/>[GET /companies/{companyId}/data/financials/balanceSheet/accounts](/assess-api#/operations/get-accounts-for-enhanced-balance-sheet) <br/>If you would like to continue using the formulas we used to offer, you can find them [here](https://docs.google.com/spreadsheets/d/1xpyQHOTQWHybOZpSnfXx54tkag0qmJ1mR76bQt9wink/edit?usp=sharing)  	|

```

2023-04-03 14:26 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories-portal.md
> +![Screenshot of Profit and loss screen that's being deprecated in Assess](/img/assess/profit-and-loss-screen-assess.png)
all the screenshots are quite small and can't be zoomed into - is that ok that they're not very clear?

2023-04-03 14:26 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories-portal.md
> +## Instructions for migration
is this really an instruction, or should the title be something to do with features?

2023-04-03 14:26 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories-portal.md
> +| Under Assess: Balance sheet screen Profit and loss screen  Ratios (at the end of Profit and loss / Balance sheet screens) Marketing screen 	| We will no longer be supporting UIs for these however y
for this bit - Under Assess: Balance sheet screen Profit and loss screen Ratios (at the end of Profit and loss / Balance sheet screens
- I am not sure how this is meant to be organized, but it's really missing the line breaks

2023-04-03 14:26 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories-portal.md
> +| Under Assess: Balance sheet screen Profit and loss screen  Ratios (at the end of Profit and loss / Balance sheet screens) Marketing screen 	| We will no longer be supporting UIs for these however y
```suggestion
| Under Assess: Balance sheet screen Profit and loss screen  Ratios (at the end of Profit and loss / Balance sheet screens) Marketing screen 	| We will no longer support UIs for these features. However, you can replicate them with more flexibility in our new Excel report. <br/> In the Codat Portal, navigate to **Companies** and select the relevant one. Under **Products**, click **Assess → Reports**, a new **Assess Report** option is available to be generated and downloaded. Use pivot tables and calculations to generate the metrics and views that you need. 	|  	|

```

2023-04-03 14:26 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories-portal.md
> +| Under Assess: Categorize accounts Under Accounting API Accounting Data → Accounts → Categorize accounts 	| If you want to recategorize accounts so the model learns and improves for your companies:
```suggestion
Use the confidence levels to decide if you want to proceed without recategorizing. See our example on how to interact with our new confidence levels. If you do not care about the model learning for your companies, you do not need to recategorize via Codat. Simply make amendments in your own environment. 	|  	|
```

also, where is this example you mentioned in the text?

2023-04-03 14:26 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories-v2-excel.md
> +| In the data export excel: Account categories sheet Categorized account balances sheet 	| Log into the Codat Portal → Select a company → Under products, click Assess → Reports A new ‘Assess Report'
please could you also format with line breaks, and format the navigation paths similarly to what I suggested in one of the previous comments

2023-04-03 14:26 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories.md
> +On the **10th July 2023**, we will be deprecating the legacy version of Account Categories and all related features. These features include:
```suggestion
On the **10th July 2023**, we will be deprecating the legacy version of Account Categories and all related features, including:

```

2023-04-03 14:26 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories.md
> +- [Clients who use Assess in the portal](docs/assess/guides/underwriting/migration-guides/deprecation-account-categories-portal)
```suggestion
- [Clients who use Assess in the Portal](docs/assess/guides/underwriting/migration-guides/deprecation-account-categories-portal)

```

2023-04-03 14:26 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories.md
> +- [Clients who use the data extract to excel in the portal](docs/assess/guides/underwriting/migration-guides/deprecation-account-categories-v2-excel)
```suggestion
- [Clients who use the data extract to Excel in the Portal](docs/assess/guides/underwriting/migration-guides/deprecation-account-categories-v2-excel)

```

2023-04-03 14:28 UTC, e-donnelly commented on docs/assess/guides/migration-guides/deprecation-account-categories-api-clients.md
> +- [GET /data/assess/accounts/categories](/assess-api#/operations/list-available-account-categories)
Better?

2023-04-03 14:28 UTC, e-donnelly commented on docs/assess/guides/migration-guides/deprecation-account-categories-api-clients.md
> +| GET /data/assess/accounts/categories 	| The supported categories have changed - you can find the latest list here.  	|
I think I figured it out. Is this better?

2023-04-03 14:40 UTC, e-donnelly commented on docs/assess/guides/migration-guides/deprecation-account-categories-api-clients.md
> +| GET /data/assess/accounts/categories 	| The supported categories have changed - you can find the latest list here.  	|
fixed

2023-04-03 16:33 UTC, e-donnelly commented on docs/assess/guides/migration-guides/deprecation-account-categories-v2-excel.md
> +| In the data export excel: Account categories sheet Categorized account balances sheet 	| Log into the Codat Portal → Select a company → Under products, click Assess → Reports A new ‘Assess Report'
Done :)

2023-04-04 12:37 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories-api.md
> +| [List suggested and confirmed account categories](/assess-api#/operations/list-accounts-categories)  <br/><br/> [Get suggested and/or confirmed categories for a specific account](/assess-api#/opera
```suggestion
| [List suggested and confirmed account categories](/assess-api#/operations/list-accounts-categories)  <br/><br/> [Get suggested and/or confirmed categories for a specific account](/assess-api#/operations/get-account-category)  	| We will not be replicating this functionality in the latest version as it’s possible for an account to have more than one category depending on the financial period.<br/>For example, a bank account could have a positive balance in one period and be categorized as an Asset, and a negative balance due to it being overdrawn in another and therefore categorized as a Liability. <br/>You can retrieve the categories per account and financial period via these endpoints:<br/>[Enhanced profit and loss accounts](/assess-api#/operations/get-accounts-for-enhanced-profit-and-loss) <br/>[Enhanced balance sheet accounts](/assess-api#/operations/get-accounts-for-enhanced-balance-sheet) 	|

```

2023-04-04 12:38 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories-api.md
> +| [Confirm categories for accounts](/assess-api#/operations/update-accounts-categories) <br/><br/> [Confirm account category for a specific account](/assess-api#/operations/update-account-category)
```suggestion
| [Confirm categories for accounts](/assess-api#/operations/update-accounts-categories) <br/><br/> [Confirm account category for a specific account](/assess-api#/operations/update-account-category)  	| You may want to recategorize accounts so that the model learns and improves for your companies. To do so:<br/>1. Log into the Codat portal <br/>2. Select a company on the **Companies** page <br/>3. Click the **Categorize Accounts** button <br/>4. Ensure the **Version** drop-down on the top right is set to _Version 3_ <br/><br/>We have revamped this screen and included new features that simplify account categorization, including Confidence level. <br/><br/> If you used to recategorize because the Enhanced Profit and Loss / Balance Sheet was not being returned due to uncategorized accounts, note that the latest endpoints do not have this restriction. <br/>If you do not need the model to learn for your companies, you do not need to recategorize via Codat and can make amendments in your own environment. <br/><br/>**Note**: In the latest version we no longer support recategorization via API. 	|

```

2023-04-04 12:42 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories-portal.md
> +### Viewing financial statements and calculating ratios
full stops either everywhere, or nowhere

2023-04-04 12:42 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories-portal.md
> +1. Log into the **Codat Portal**
```suggestion
1. Log into the **Codat Portal**.

```

2023-04-04 12:42 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories-portal.md
> +2. Select a company on the **Companies** page
```suggestion
2. Select a company on the **Companies** page.

```

2023-04-04 12:42 UTC, pzaichkina commented on docs/assess/guides/migration-guides/deprecation-account-categories-portal.md
> +3. Under products, click **Assess**, and then **Reports**
```suggestion
3. Under Products, click **Assess**, and then **Reports**.

```

2023-04-04 14:20 UTC, pzaichkina approved these changes

2023-04-04 14:23 UTC, merged