Add new product update
codatio/codat-docs pull request #289
Opened 2023-04-04 15:54 UTC by mcclowes

# Description

New post

2023-04-04 16:39 UTC, d-laing requested changes
Great to highlight these new features!

2023-04-04 16:39 UTC, d-laing commented on blog/230404-product-update.md
> +We've improvemed our data type coverage for a number of integrations.
```suggestion
We've improved our data type coverage for a number of integrations.
```

2023-04-04 16:39 UTC, d-laing commented on blog/230404-product-update.md
> +- Pull 'Jobs' on Tracking Categories
```suggestion
- Pull "Jobs" on Tracking Categories
```

2023-04-04 16:39 UTC, d-laing commented on blog/230404-product-update.md
> +- We've added support for Pushing Direct Cost attachments
```suggestion
- We've added support for pushing Direct Cost attachments
```

2023-04-04 16:39 UTC, d-laing commented on blog/230404-product-update.md
> +Don't forget about these immenent deprecations:
```suggestion
Don't forget about these imminent deprecations:
```

2023-04-05 09:10 UTC, d-laing commented on blog/230404-product-update.md
> +tags: ["Deprecation"]
Just checked: should be `Product` and `Update`.

2023-04-05 10:34 UTC, pzaichkina commented on blog/230404-product-update.md
> +The next round of deprecations will be in July:
I guess this now also needs to have the Assess deprecation

2023-04-05 10:35 UTC, pzaichkina commented on blog/240101-draft-update.md
> +tags: ["Deprecation"]
yeah the tag should probably be Product and Update

2023-04-05 11:14 UTC, merged