Account management updates
codatio/codat-docs pull request #296
Opened 2023-04-05 15:35 UTC by pzaichkina

# Description

Updates to the account management page - includes account settings and new option to change passwords.

## Type of change

Please delete options that are not relevant.

- [X] New document(s)/updating existing
- [ ] Fixes
- [ ] Styling
- [ ] Bug fix (non-breaking change which fixes an issue)

## Reviews and merging

You are responsible for getting your PR merged. Address review comments promptly and **make sure to merge the PR when ready**.
Feel free to 'Enable automerge' - your PR will automatically merge when accepted and passing the build.

2023-04-05 16:09 UTC, mcclowes requested changes

2023-04-05 16:09 UTC, mcclowes commented on docs/other/portal/account-management.md
> +If you forgot your password and are looking to reset it, perform the following steps:
```suggestion
If you have forgotten your password and are looking to reset it:
```

2023-04-05 16:09 UTC, mcclowes commented on static/img/other-guides/0012-acct-mgt-access.png
Looks weird with the browser bar. You can disable this

2023-04-06 10:23 UTC, d-laing requested changes
Clear and concise.

2023-04-06 10:23 UTC, d-laing commented on docs/other/portal/account-management.md
> +In the **Profile** section, you can change the name associated with the account, and confirm your involvement with the technical implementation of your Codat solution. Remember to press **Save change
```suggestion
In the **Profile** section, you can change the name associated with the account, and confirm your involvement with the technical implementation of your Codat solution. Remember to click **Save changes** when you are done. 
```

2023-04-06 10:23 UTC, d-laing commented on docs/other/portal/account-management.md
> +3. Finally, press **Update password** to save your changes.
```suggestion
3. Finally, click **Update password** to save your changes. 
```

2023-04-06 10:23 UTC, d-laing commented on docs/other/portal/account-management.md
> +3. Finally, press **Update password** to save your changes.
**Update password** is styled as a button, so I think we should use "click".

2023-04-06 10:23 UTC, d-laing commented on docs/other/portal/account-management.md
>  2. Next, enter the email you registered with.
I don't think this short procedure needs "next" and "finally". I appreciate this text was already there!

2023-04-06 12:02 UTC, mcclowes approved these changes

2023-04-06 12:03 UTC, merged