Replace underwriting with lending or loan qualification
codatio/codat-docs pull request #299
Opened 2023-04-05 17:51 UTC by mcclowes

2023-04-05 18:34 UTC, pzaichkina requested changes

2023-04-05 18:34 UTC, pzaichkina commented on docs/assess/guides/loan-qualification/introduction.md
> +The codebase uses Codat and its [Assess](/assess/overview) product to make a lending decision. We will walk you through the setup in the Portal and the code [next](/assess/guides/lending/setting-up).
so is it lending or loan qualification that should be in the URL path?

2023-04-05 18:34 UTC, pzaichkina commented on docs/assess/guides/loan-qualification/process-loan.md
> +![](/img/use-cases/loan qualification/sandbox-credentials-modal.png)
your find and replace broke our image links :)

2023-04-05 18:34 UTC, pzaichkina commented on docs/assess/guides/loan-qualification/process-loan.md
> +![](/img/use-cases/loan qualification/sandbox-credentials-modal.png)
```suggestion
![](/img/use-cases/loan-qualification/sandbox-credentials-modal.png)
```

2023-04-05 18:34 UTC, pzaichkina commented on docs/assess/guides/loan-qualification/process-loan.md
> +![](/img/use-cases/loan qualification/0000-acct-categorization-modal-06-03-2023.png)
```suggestion
![](/img/use-cases/loan-qualification/0000-acct-categorization-modal-06-03-2023.png)
```

2023-04-05 18:34 UTC, pzaichkina commented on docs/assess/guides/loan-qualification/process-loan.md
> +![](/img/use-cases/loan qualification/0000-categorization-screen.png)
```suggestion
![](/img/use-cases/loan-qualification/0000-categorization-screen.png)
```

2023-04-05 18:34 UTC, pzaichkina commented on docs/assess/guides/loan-qualification/process-loan.md
> +  We provide [detailed information](/assess/guides/loan qualification/uw-decision) about the loan qualification logic we included in our demo app, and how exactly the financial data is fetched.
```suggestion
  We provide [detailed information](/assess/guides/loan-qualification/uw-decision) about the loan qualification logic we included in our demo app, and how exactly the financial data is fetched. 
```

2023-04-06 09:14 UTC, mcclowes commented
Apologies @pzaichkina , very messy on my part

2023-04-06 10:05 UTC, d-laing approved these changes
All looks good.

2023-04-06 10:53 UTC, pzaichkina approved these changes

2023-04-06 10:53 UTC, merged