Tax Rate information update
codatio/codat-docs pull request #309
Opened 2023-04-12 16:10 UTC by Amy-Roberts

Tax Rate information update

# Description
Tax Rate information update 

Include a summary of the new content you're adding or the reason for the change. 
Include relevant context.
Don't link to work items.

## Type of change

Please delete options that are not relevant.

- [ / ] New document(s)/updating existing
- [ ] Fixes
- [ ] Styling
- [ ] Bug fix (non-breaking change which fixes an issue)

## Reviews and merging

You are responsible for getting your PR merged. Address review comments promptly and **make sure to merge the PR when ready**.
Feel free to 'Enable automerge' - your PR will automatically merge when accepted and passing the build.

2023-04-12 16:28 UTC, pzaichkina commented on docs/sync-for-expenses/configandcategorize.md
> +Accounting systems typically store a set of taxes and associated rates within the accounting package. This means that users don't have to look up or remember the rates for each type of tax. For examp
```suggestion
Accounting systems typically store a set of taxes and associated rates within the accounting package. This means that users don't have to look up or remember the rates for each type of tax. For example, applying the tax "UK sales VAT" to line items of an invoice adds the correct rate of 20%. 
```

2023-04-12 16:28 UTC, pzaichkina requested changes
please address the comments

2023-04-13 09:33 UTC, d-laing requested changes
Nice additions. I added review comments.

2023-04-13 09:33 UTC, d-laing commented on docs/sync-for-expenses/configandcategorize.md
> +Accounting systems typically store a set of taxes and associated rates within the accounting package. This means that users don't have to look up or remember the rates for each type of tax. For examp
```suggestion
Accounting systems typically store a set of taxes and associated rates within the accounting package. This means users don't have to look up or remember the rate for each type of tax. For example, applying the tax "UK sales VAT" to the line items of an invoice adds the correct tax rate of 20%. 
```

2023-04-13 09:33 UTC, d-laing commented on docs/sync-for-expenses/configandcategorize.md
> +Assigning a tax rate to a transaction is mandatory unless the transaction is a [transfer](/sync-for-expenses/sync-process/expense-transactions#transaction-types). In some cases, your customers might
```suggestion
Assigning a tax rate to a transaction is mandatory unless the transaction is a transferIn or transferOut (see [Transaction types](/sync-for-expenses/sync-process/expense-transactions#transaction-types). In some cases, your customers might not need to track tax on expenses. We recommend assigning a default tax code for 0% from the accounting package for those transactions.
```

2023-04-13 09:33 UTC, d-laing commented on docs/sync-for-expenses/configandcategorize.md
> +Assigning a tax rate to a transaction is mandatory unless the transaction is a [transfer](/sync-for-expenses/sync-process/expense-transactions#transaction-types). In some cases, your customers might
I don't think the link text of "transfer" is clear enough. I thought it was going to direct me to the data model.

2023-04-13 09:35 UTC, d-laing commented on docs/sync-for-expenses/configandcategorize.md
> +Assigning a tax rate to a transaction is mandatory unless the transaction is a [transfer](/sync-for-expenses/sync-process/expense-transactions#transaction-types). In some cases, your customers might
Use "those" to refers to things which have already been mentioned in the sentence :-) [1]

[1] https://www.collinsdictionary.com/dictionary/english/those

2023-04-19 15:49 UTC, mcclowes approved these changes

2023-04-20 08:07 UTC, merged