Created single page for deleting QBO objects
codatio/codat-docs pull request #314
Opened 2023-04-13 12:54 UTC by DaveHCodat

# Description

Updating delete Journal Entries page to single page covering all QBO delete functionality across JEs, Bills and Invoices.

## Type of change

Please delete options that are not relevant.

- [x ] New document(s)/updating existing
- [ ] Fixes
- [ ] Styling
- [ ] Bug fix (non-breaking change which fixes an issue)

## Reviews and merging

You are responsible for getting your PR merged. Address review comments promptly and **make sure to merge the PR when ready**.
Feel free to 'Enable automerge' - your PR will automatically merge when accepted and passing the build.

2023-04-13 13:47 UTC, mcclowes commented on docs/integrations/accounting/quickbooksonline/accounting-quickbooksonline-delete-journal-entries.md
> +title: "Delete Objects from QuickBooks Online"
```suggestion
title: "Delete data from QuickBooks Online"
```

2023-04-14 08:34 UTC, d-laing requested changes

2023-04-14 08:34 UTC, d-laing commented on docs/integrations/accounting/quickbooksonline/accounting-quickbooksonline-delete-journal-entries.md
> +## Deleting Journal Entries
```suggestion
## Deleting Journal entries
```

2023-04-14 08:34 UTC, d-laing commented on docs/integrations/accounting/quickbooksonline/accounting-quickbooksonline-delete-journal-entries.md
>  The _Delete Journal Entries_ endpoint allows you to delete a specified Journal Entry from QuickBooks Online.
```suggestion
The _Delete Journal entries_ endpoint allows you to delete a specified Journal entry from QuickBooks Online.
```

2023-04-14 08:34 UTC, d-laing commented on docs/integrations/accounting/quickbooksonline/accounting-quickbooksonline-delete-journal-entries.md
>  3. Check the Journal Entry no longer exists in the QBO UI.
```suggestion
3. Check the Journal entry no longer exists in the QBO UI.
```

2023-04-14 09:57 UTC, d-laing approved these changes

2023-04-17 12:13 UTC, merged