Sign up with Xero: new page
codatio/codat-docs pull request #316
Opened 2023-04-13 15:21 UTC by pzaichkina

# Description

New page added to cover the Sign Up with Xero content from Zendesk in the public docs. 
docs/integrations/accounting/xero/xero-sign-up-flow

## Type of change

- [X] New document(s)/updating existing

2023-04-14 09:31 UTC, mcclowes commented on docs/integrations/accounting/xero/xero-sign-up-flow.md
> +## When to build?
I really like this header convention 👍

2023-04-14 09:31 UTC, mcclowes commented on docs/integrations/accounting/xero/xero-sign-up-flow.md
> +### Utilize Xero data
Can we be more specific for this header?

2023-04-14 11:16 UTC, pzaichkina commented on docs/integrations/accounting/xero/xero-sign-up-flow.md
> +   Call our `GET https://api.codat.io/profile/syncSettings` endpoint and pick up the `clientId` returned in the response. For Xero, the `platfromKey` value is `gbol`, as captured in our [accounting p
@mcclowes this is the endpoint that is not in our API that I mentioned in slack

2023-04-17 08:53 UTC, d-laing requested changes
Looks good. I made a few comments.

2023-04-17 08:53 UTC, d-laing commented on docs/integrations/accounting/xero/xero-sign-up-flow.md
> +   Note that this URL should also be used as a response to _6. Purchase/sign up page URL_ in your App Store listing.
```suggestion
   Note that this URL should also be used as a response to checkpoint _6. Purchase/sign up page URL_ in your App Store listing. 
```

2023-04-18 09:38 UTC, d-laing approved these changes
The additions to the intro look good.

2023-04-18 13:07 UTC, merged