Example of what the video guides might look like
codatio/codat-docs pull request #341
Opened 2023-04-27 15:38 UTC by mcclowes

# Description

Thoughts?

2023-04-28 16:10 UTC, d-laing requested changes
Few comments on the text.

2023-04-28 16:10 UTC, d-laing commented on docs/introduction/first-ten-minutes.md
> +title: "Video: Your first ten minutes with Codat"
Would be good to see how this wraps in the sidebar.

2023-04-28 16:10 UTC, d-laing commented on docs/introduction/first-ten-minutes.md
> +description: "From signing up to syncing in 10 minutes."
```suggestion
description: "From signing up to syncing data in 10 minutes."
```

2023-04-28 16:10 UTC, d-laing commented on docs/introduction/first-ten-minutes.md
> +In this video we'll sign up to Codat, set up the Xero integration and pull data from Xero.
```suggestion
In this video we'll sign up to Codat, set up the Xero integration, and pull data from Xero.
```

2023-05-02 09:11 UTC, mcclowes commented on docs/introduction/first-ten-minutes.md
> +title: "Video: Your first ten minutes with Codat"
It's definitely too long yeah

2023-05-11 14:14 UTC, merged