Assess metrics template
codatio/codat-docs pull request #352
Opened 2023-05-05 10:56 UTC by igurney-codat

Create stand alone page (not linked currently) but this will be linked from UI and will be expanded later

2023-05-05 16:52 UTC, d-laing requested changes
Great feature. I made a few revisions.

2023-05-05 16:52 UTC, d-laing commented on static/documents/.gitignore
> +~$*
What does this ignore?

2023-05-05 16:52 UTC, d-laing commented on docs/assess/excel/enhanced-financials-report.md
> +description: "Download the enhanced financials report to Excel"
```suggestion
description: "Download the Enhanced Financials report to Excel"
```

2023-05-05 16:52 UTC, d-laing commented on docs/assess/excel/enhanced-financials-report.md
> +sidebar_label: "Enhanced financials report"
```suggestion
sidebar_label: "Enhanced Financials report"
```

2023-05-05 16:52 UTC, d-laing commented on docs/assess/excel/enhanced-financials-report.md
> +title: "Enhanced Financials Report"
```suggestion
title: "Enhanced Financials Excel Report"
```

2023-05-05 16:52 UTC, d-laing commented on docs/assess/excel/enhanced-financials-report.md
> +Our enhanced financials Excel report is designed to give you the same data you would get via the API.  You can use this report to test some companies and familiarise yourself with the data before bui
```suggestion
Our Enhanced Financials Excel report gives you the same data you'd get from the [Enhanced Financials endpoints](/assess/enhanced-financials/overview), but in an Excel workbook.  You can use the report to test some companies and familiarise yourself with the data before building to the equivalent API endpoints.
```

2023-05-05 16:52 UTC, d-laing commented on docs/assess/excel/enhanced-financials-report.md
> +The report contains data based on the data types you have enabled. If a data type is missing, the data associated with it will be omitted.
```suggestion
The Enhanced Financials Excel report contains data from the currently enabled data types. If a data type is not enabled, the data associated with it is omitted.
```

2023-05-05 16:52 UTC, d-laing commented on docs/assess/excel/enhanced-financials-report.md
> +The Assess Report can be generated via API or through [Codat's Portal](/assess/portal/overview#reports).  The [Excel reports](/assess/excel/overview) page describes how to generate and download the r
```suggestion
You can generate the Enhanced Financials Excel report using the API or the Codat Portal (for details, see [Reports](/assess/portal/overview#reports)). The [Assess reports in Excel](/assess/excel/overview) article describes how to generate and download the report using the API.
```

2023-05-05 16:52 UTC, d-laing commented on docs/assess/excel/enhanced-financials-report.md
> +We recommend creating a pivot table and grouping by category Level 1-5 to replicate a financial statement view.  Users can also create formulas for financial ratios.
```suggestion
To get the most out of the report, try creating a pivot table and grouping the data by category Level 1-5 to replicate a financial statement view. You can also create formulas to calculate financial ratios.
```

2023-05-05 16:52 UTC, d-laing commented on docs/assess/excel/enhanced-financials-report.md
> +We have created a [Metrics Template](/documents/assess-metrics.xlsx) that allows users to paste data from the enhanced financials report to calculate key financial metrics and ratios.
```suggestion
We've also created a [Metrics Template Excel file](/documents/assess-metrics.xlsx). You can paste data into this file from the Enhanced Financials report to calculate key financial metrics and ratios.
```

2023-05-05 16:52 UTC, d-laing commented on docs/assess/excel/enhanced-financials-report.md
> +This report contains an output of the following feature:
```suggestion
The report contains the output of the following features:
```

2023-05-05 16:52 UTC, d-laing commented on docs/assess/excel/enhanced-financials-report.md
> +This report requires an accounting integration with the following datatypes enabled:
```suggestion
The report requires an accounting integration with the following data types enabled:
```

2023-05-09 08:40 UTC, igurney-codat commented on static/documents/.gitignore
> +~$*
This ignores files starting with ~$ and I have added this as if you open the Excel document it will create a temporary file in the same folder which could then be uploaded to Git.  This prevents this from happening by ignoring it.

2023-05-09 09:23 UTC, igurney-codat reviewed
Changed have been made

2023-05-09 09:37 UTC, d-laing approved these changes
Changes look good.

2023-05-09 09:37 UTC, merged