Updated delete sections.
codatio/codat-docs pull request #368
Opened 2023-05-11 15:03 UTC by dcoplowe

# Description

Migrated delete information to OAS. 

## Type of change

Please delete options that are not relevant.

- [x] New document(s)/updating existing
- [ ] Fixes
- [ ] Styling
- [ ] Bug fix (non-breaking change which fixes an issue)

## Reviews and merging

You are responsible for getting your PR merged. Address review comments promptly and **make sure to merge the PR when ready**.
Feel free to 'Enable automerge' - your PR will automatically merge when accepted and passing the build.

2023-05-11 16:39 UTC, d-laing requested changes

2023-05-11 16:39 UTC, d-laing commented on docs/integrations/accounting/quickbooksonline/accounting-quickbooksonline-delete-journal-entries.md
I feel there should be a link or reference to the functionality from here. Especially when delete endpoints are at such an early stage.

2023-05-11 16:39 UTC, d-laing commented on docs/integrations/accounting/netsuite/accounting-netsuite-how-deleting-bill-payments-works.md
> +sidebar_label: "How deleting Bill payments works"
"Delete Bill payments" is maybe more suitable for the sidebar.

2023-05-11 21:18 UTC, mcclowes commented
Isn't the point of the changes you've made that we don't have a QB OR Netsuite specific page on deletion?

2023-05-16 15:48 UTC, mcclowes requested changes

2023-05-16 15:48 UTC, mcclowes commented on sidebars/integrations.js
> +          "integrations/accounting/netsuite/accounting-netsuite-how-deleting-bill-payments-works",
Shouldn't be under netsuite

2023-05-17 09:28 UTC, mcclowes approved these changes

2023-05-17 09:29 UTC, merged