Use American English, add apostrophes and hyphens
codatio/codat-docs pull request #39
Opened 2023-02-08 17:14 UTC by jbyrnecodat

# Description

Correcting some terms to use American English, tweaking the use of apostrophes and hyphens in a few cases. Also capitalises some words where appropriate.

## Type of change

Please delete options that are not relevant.

- [ ] New document(s)/updating existing
- [x] Fixes
- [ ] Styling
- [ ] Bug fix (non-breaking change which fixes an issue)

2023-02-08 17:50 UTC, mcclowes requested changes
There seem to be some issues with the changes you made

2023-02-08 17:50 UTC, mcclowes commented on docs/bank-feed-api/overview.md
> +In Codat's API, bank feeds are represented as [Bank transactions](/data-model/accounting/-banktransactions), which are pushed from a source to a target bank account in chronological order. Bank feeds
This URL was correct previously? And the new one doesn't exist

2023-02-08 17:50 UTC, mcclowes commented on docs/bank-feed-api/overview.md
> +:::Note Product feedback
Capitalizing doesn't work - 
![image](https://user-images.githubusercontent.com/4573407/217610914-5ecf4309-7754-48d8-992e-b05ac6954aa9.png)

2023-02-08 17:50 UTC, mcclowes commented on docs/bank-feed-api/qbo-bank-feeds/bank-feed-qbo-bank-feeds-push-bank-transactions.md
> +1. Push bank transactions from an SMB user's connected bank account using the <a className="external" href="https://api.codat.io/swagger/index.html#/BankAccounts/post_companies__companyId__connection
Old URL was correct

2023-02-09 10:01 UTC, d-laing commented on docs/bank-feed-api/overview.md
> +:::Note Product feedback
Also applies to Cautions, etc.

2023-02-09 10:04 UTC, jbyrnecodat commented on docs/bank-feed-api/overview.md
> +In Codat's API, bank feeds are represented as [Bank transactions](/data-model/accounting/-banktransactions), which are pushed from a source to a target bank account in chronological order. Bank feeds
Sorry, not sure what happened here. I didn't touch this but it may have been an issue with keeping my fork up-to-date after others merged changes. Anyway, should be resolved now.

2023-02-09 10:05 UTC, jbyrnecodat commented on docs/bank-feed-api/overview.md
> +:::Note Product feedback
Oops, I've updated these so they are properly capitalised now.

2023-02-17 15:00 UTC, mcclowes requested changes
Just one regression on an image url

2023-02-17 15:00 UTC, mcclowes commented on docs/integrations/accounting/xero/xero-app-partner-program.mdx
> +| Requirement                                                                                           | Recommendations
Not 100% sure this way of formatting tables is ideal, but not a deal breaker

2023-02-17 15:21 UTC, jbyrnecodat commented on docs/integrations/accounting/xero/xero-app-partner-program.mdx
> +| Requirement                                                                                           | Recommendations
Yeah I think that was Prettier auto-formatting

2023-02-28 18:07 UTC, mcclowes commented
Do you still want to merge this?

2023-03-01 08:36 UTC, jbyrnecodat commented
> Do you still want to merge this?

Yes please! I've resolved the conflicts now.

2023-03-03 12:19 UTC, mcclowes requested changes
Just a few quick fixes

2023-03-03 12:19 UTC, mcclowes commented on docs/index.mdx
> -    <p>Embedded accounting integrations for corporate card providers. Launch new accounting integrations faster and save on ongoing maintenance by standardizing how you sync with bookkeeping software
We've lost a key paragraph here

2023-03-03 12:19 UTC, mcclowes commented on docs/integrations/accounting/xero/xero-app-partner-program.md
> +Use our interactive checkpoint list to track your progress. It will be saved in your browser.
weird, not a bit issue though

2023-03-03 12:19 UTC, mcclowes commented on docs/introduction/migration.md
> +Codat's API allows you to provide tokens for a subset of our integrations which will allow you to self-manage a migration.
Good spot

2023-03-03 12:19 UTC, mcclowes commented on docs/introduction/webhooks/core-rules-types.md
> -
These spaces were intentional

2023-03-03 12:19 UTC, mcclowes commented on docs/introduction/webhooks/core-rules-webhooksecurity.md
> +## Enable webhook security via the API
Was this added on purpose? This might be readding something that was removed on purpose?

2023-03-03 13:10 UTC, jbyrnecodat commented on docs/introduction/webhooks/core-rules-webhooksecurity.md
> +## Enable webhook security via the API
Yeah I think that's what happened. Probably a merge gone wrong.

2023-03-03 13:13 UTC, jbyrnecodat commented on docs/introduction/webhooks/core-rules-types.md
> -
Oops. Fixed.

2023-03-10 19:03 UTC, pzaichkina commented
one pending change from Max's comment @jbyrnecodat

2023-03-13 16:58 UTC, jbyrnecodat commented
> one pending change from Max's comment @jbyrnecodat

Forgot to mark it as resolved. All done :)

2023-03-13 18:16 UTC, mcclowes approved these changes

2023-03-13 18:16 UTC, merged