updated overview page for payables
codatio/codat-docs pull request #413
Opened 2023-05-24 13:14 UTC by jmyorston

# Description

updated the payables page - changed some of the text and added feature cards.
`/usecases/summary/automating-payables`

## Type of change

Please delete options that are not relevant.

- [x] New document(s)/updating existing
- [ ] Fixes
- [ ] Styling
- [ ] Bug fix (non-breaking change which fixes an issue)

2023-05-24 13:44 UTC, pzaichkina requested changes

2023-05-24 13:44 UTC, pzaichkina commented on docs/usecases/summary/automating-payables.mdx
> +description: "Streamline your customers' accounts payable workflow."
```suggestion
description: "Streamline your customers' accounts payable workflow"

```

2023-05-24 13:44 UTC, pzaichkina commented on docs/usecases/summary/automating-payables.mdx
> +By integrating your customers accounting software, supplier information and invoices and payments can be easily kept in sync.
```suggestion
By integrating your customers' accounting software, their supplier information, invoices, and payments can be easily kept in sync. 

```

2023-05-24 13:44 UTC, pzaichkina commented on docs/usecases/summary/automating-payables.mdx
> +This automation replaces manual tasks and eliminates duplication of effort, making it easier for your customers and freeing up time for them to concentrate on running their business.
making what easier for the customers? this part of the phrase does not currently show any value. 
I think it's sufficient to just say 
"This automation replaces manual tasks and eliminates duplication of effort,  freeing up your customers' time so they can concentrate on running their business."

2023-05-24 13:44 UTC, pzaichkina commented on docs/usecases/summary/automating-payables.mdx
> +      <h3>Create Bills</h3>
```suggestion
      <h3>Create bills</h3>

```

2023-05-24 13:44 UTC, pzaichkina commented on docs/usecases/summary/automating-payables.mdx
> +      <h3>Removing Repetition</h3>
```suggestion
      <h3>Removing repetition</h3>

```

2023-05-24 13:44 UTC, pzaichkina commented on docs/usecases/summary/automating-payables.mdx
> +#### Supported Features
```suggestion
#### Supported features

```

2023-05-24 13:44 UTC, pzaichkina commented on docs/usecases/summary/automating-payables.mdx
> +      Enable a vendor bill to be created within their application and then synchronized to customers’ accounting platforms.
```suggestion
      Enable your customers to create a vendor bill within their application, and synchronize it to their accounting platform.
```

2023-05-24 13:44 UTC, pzaichkina commented on docs/usecases/summary/automating-payables.mdx
> +      Remove repetition by reconciling the payments against supplier invoices in your customers accoutning software.
```suggestion
      Reconcile payments against supplier invoices in your customers' accounting software, reducing the chance of duplication.
```

2023-05-24 14:02 UTC, jmyorston commented on docs/usecases/summary/automating-payables.mdx
> +This automation replaces manual tasks and eliminates duplication of effort, making it easier for your customers and freeing up time for them to concentrate on running their business.
@pzaichkina great idea - updated

2023-05-24 14:08 UTC, d-laing commented on docs/usecases/summary/automating-payables.mdx
> +By integrating your customers accounting software, supplier information and invoices and payments can be easily kept in sync.
Alternative phrasing:

Integrate with your customers' accounting software to easily keep their supplier information, invoices, and payments in sync.

2023-05-25 09:13 UTC, pzaichkina approved these changes

2023-05-25 09:13 UTC, merged