Zoho Books updates
codatio/codat-docs pull request #72
Opened 2023-02-13 18:03 UTC by jepmatthews

# Description

Fix some links, fix table and updated some text in the rate limit section 

## Type of change

Please delete options that are not relevant.

- [x] New document(s)/updating existing
- [x] Fixes
- [x] Styling

2023-02-13 19:19 UTC, mcclowes approved these changes
Thanks for these changes!

2023-02-13 19:19 UTC, mcclowes commented on docs/integrations/accounting/zoho-books/zoho-book-limits.md
> +| Data type pulled  | Fields excluded                 |
🙌

2023-02-14 11:17 UTC, d-laing requested changes
Thanks. I made a few suggestions.

2023-02-14 11:17 UTC, d-laing commented on docs/integrations/accounting/zoho-books/zoho-book-limits.md
> +Our Zoho Books integration works within these limits to minimize the performance impact of pulling and pushing large volumes of data. It tries to maximise the number of records retrieved per API call
```suggestion
Our Zoho Books integration works within these limits to minimize the performance impact of pulling and pushing large volumes of data. To do so, the integration maximises the number of records retrieved per API call for most data types. However, for certain data types, the integration can only fetch a single record for each API call to Zoho Books, impacting performance. This also applies if the restrictions on pulling reduced datasets described above are removed.
```

2023-02-14 11:17 UTC, d-laing commented on docs/integrations/accounting/zoho-books/zoho-book-limits.md
> +If the cumulative number of API calls to the organisation you are trying to link to exceeds the daily limit, you might encounter the following issues:
```suggestion
If the cumulative number of API calls to the organization you are trying to link to exceeds the daily limit, you might encounter the following issues:
```

2023-02-14 11:18 UTC, d-laing commented on docs/integrations/accounting/zoho-books/zoho-book-limits.md
> +Our Zoho Books integration works within these limits to minimize the performance impact of pulling and pushing large volumes of data. It tries to maximise the number of records retrieved per API call
I have tried to break up the information a bit.

2023-02-14 11:19 UTC, jepmatthews commented on docs/integrations/accounting/zoho-books/accounting-zoho-books.md
> +By default, reduced datasets are pulled for the Bills, Credit Notes, Customers, and Invoices data types. For more information, see [Zoho Books limits and reduced data pulls](zoho-book-limits).
Happy to do this, but if you move the whole Zoho books folder the links wouldn't need to be updated if you did it like this, whereas they would if you used the full path, surely this is better if we expect the relative paths of these files never to change?

2023-02-14 11:32 UTC, d-laing commented on docs/integrations/accounting/zoho-books/accounting-zoho-books.md
> +By default, reduced datasets are pulled for the Bills, Credit Notes, Customers, and Invoices data types. For more information, see [Zoho Books limits and reduced data pulls](zoho-book-limits).
Good point. Leave the relative paths for now and we'll discuss as a team.

2023-02-14 11:53 UTC, jepmatthews commented on docs/integrations/accounting/zoho-books/zoho-book-limits.md
> +Our Zoho Books integration works within these limits to minimize the performance impact of pulling and pushing large volumes of data. It tries to maximise the number of records retrieved per API call
```suggestion
Our Zoho Books integration works within these limits to minimize the performance impact of pulling and pushing large volumes of data. To do so, the integration maximises the number of records retrieved per API call for most data types. However, for certain data types, the integration can only fetch a single record for each API call to Zoho Books, impacting performance. This also applies to additional data types if the restrictions on pulling reduced datasets described above are removed.```

2023-02-14 11:57 UTC, jepmatthews commented on docs/integrations/accounting/zoho-books/zoho-book-limits.md
> +Our Zoho Books integration works within these limits to minimize the performance impact of pulling and pushing large volumes of data. It tries to maximise the number of records retrieved per API call
Perhaps this is over picky but just wanted to add that it affected the specific data types where you remove restrictions (that's probably obvious but just wanted to make clear), does that wording seem reasonable. Also happy to go with your wording if you think it's clearer

2023-02-14 12:45 UTC, d-laing commented on docs/integrations/accounting/zoho-books/zoho-book-limits.md
> +Our Zoho Books integration works within these limits to minimize the performance impact of pulling and pushing large volumes of data. It tries to maximise the number of records retrieved per API call
No, that makes sense - please change. I thought the removal of restrictions by Support applied to all data types (but should have checked with you first).

2023-02-14 16:04 UTC, merged