Lending API improvements
codatio/codat-docs pull request #791
Opened 2023-09-22 15:52 UTC by pzaichkina

# Description

Minor additions to the Lending API Get started page

## Type of change
- [X] New document(s)/updating existing

2023-09-25 09:43 UTC, mcclowes requested changes

2023-09-25 09:43 UTC, mcclowes commented on docs/lending/get-started.md
> +Our Lending API supports the data collection step of your lending journey, which starts in your own web application. Enable Lending API and configure it, then utilize our authorization component in y
I don't think we've ever said 'authorization component' before? Can we say embedded link SDK or something, and add a link to the relevant page?

2023-09-25 09:43 UTC, mcclowes commented on docs/lending/get-started.md
> +As a prerequisite for data collection, you need to create a Codat company and connect it to a data source (for example, an accounting platform). The company represents your SMB customer's business th
```suggestion
Before you can collect your SMB customer's data, you need to create a Codat company and connect it to a data source (for example, an accounting platform). The company represents your customer's business that is sharing access to their data. 
```
Style-wise, I would prefer less formal language here

Also if we merge in the glossary PR then that might help here?

2023-09-25 09:43 UTC, mcclowes commented on docs/lending/get-started.md
> +To establish a connection to a data source and sync business data, your customer must grant you access. They can do so using our [Link auth flow](/auth-flow/overview) solution, which we recommend you
Link auth flow - make consistent with the language early

2023-09-25 09:43 UTC, mcclowes commented on docs/lending/get-started.md
> +Once the connection is established, Codat will perform the initial syncs for the data types you have previously enabled. You can use the `New company synchronised` [webhook](/using-the-api/webhooks/c
Enabled isn't a thing

```suggestion
Once the connection is established, Codat will retrieve data based of your data type settings (where you have previously set 'fetch on first link'). You can use the `New company synchronised` [webhook](/using-the-api/webhooks/core-rules-types#new-company-synchronized) to get notified once these initial syncs are complete, and at least one of them is successful.
```

2023-09-26 12:32 UTC, dcoplowe approved these changes

2023-09-26 12:56 UTC, mcclowes commented on docs/lending/get-started.md
> +We recommend you fully embed the Link auth flow in your experience by using our [Embedded Link](/auth-flow/authorize-embedded-link) SDK in your front-end code. You can also choose our out-of-the-box
Front-end or frontend

2023-09-26 12:56 UTC, merged