Sync for Payables
codatio/codat-docs pull request #889
Opened 2023-11-20 15:21 UTC by pzaichkina

# Description

Major product docs rework for Sync for Payables.

## Type of change

- [X] New document(s)/updating existing
- [X] Fixes
- [X] Styling
- [ ] Bug fix (non-breaking change which fixes an issue)

2023-11-20 20:02 UTC, dcoplowe requested changes

2023-11-20 20:02 UTC, dcoplowe commented on docs/payables/guides/bill-pay/how-the-demo-app-works.md
> +    backend ->> codat: Fetch bills
```suggestion
    backend ->> codat: Get/list bills
```

2023-11-20 20:02 UTC, dcoplowe commented on docs/payables/guides/bill-pay/how-the-demo-app-works.md
> +    backend ->> codat: Fetch accounts
```suggestion
    backend ->> codat: Get/list accounts
```

2023-11-21 12:18 UTC, pzaichkina commented on docs/payables/mapping.md
> +```http
no. these are accounting accounts, not bank feeds accounts

2023-11-21 12:19 UTC, pzaichkina commented on docs/payables/payments.md
> +In this diagram, we have summarized approaches to bill payments and reconciliation that are available to you via Sync for Payables. Next, we will go through those options in detail.
i'll leave it there for now and will ask Jake for a diagram as a follow up

2023-11-21 12:20 UTC, pzaichkina commented on docs/payables/get-started.md
> +graph TD
the reason it's not a sequence diagram is because some of this stuff can be done in any order, as long as it happens before a bill is paid. that's what we are trying to represent

2023-11-21 16:59 UTC, dcoplowe approved these changes

2023-11-21 16:59 UTC, merged