Sidebars: Add on prem setup connectors to nav
codatio/codat-docs pull request #97
Opened 2023-02-16 11:07 UTC by d-laing

# Description

Please include a summary of the new content you're adding or the reason for the change. Please include relevant context.

## Type of change

Please delete options that are not relevant.

- [ ] New document(s)/updating existing
- [ ] Fixes
- [ ] Styling
- [ ] Bug fix (non-breaking change which fixes an issue)

2023-02-16 13:27 UTC, d-laing commented on sidebars/commerce-api.js
> -    href: "/commerce-api",
I reordered these attributes to match the others.

2023-02-16 16:09 UTC, mcclowes requested changes

2023-02-16 16:09 UTC, mcclowes commented on sidebars/commerce-api.js
> +    href: "/integrations/commerce/overview",
Pretty sure all of these should not have the proceeding `/`

2023-02-16 16:09 UTC, mcclowes commented on sidebars/commerce-api.js
> +    href: "/integrations/commerce/overview",
Throughout all of the sidebar pretty much

2023-02-16 17:13 UTC, d-laing commented on sidebars/commerce-api.js
> +    href: "/integrations/commerce/overview",
Hmm, OK. These links are currently broken though, e.g. https://codat-docs.vercel.app/commerce-api/overview

Commerce data model
Commerce integrations

2023-02-17 12:32 UTC, mcclowes approved these changes

2023-02-17 12:32 UTC, mcclowes commented on sidebars/commerce-api.js
> +    href: "/integrations/commerce/overview",
I was wrong, sorry!

2023-02-17 14:47 UTC, merged